Added another game
VMistry/Sparta_Game pull request #5
Opened 2018-08-14 16:36 UTC by VMistry

I have done a lot in this one...
- added another page to the website
- Created nav bar
- Linked the two pages.

2018-08-14 18:23 UTC, AEJackson requested changes

2018-08-14 18:23 UTC, AEJackson commented on Game1/Game1.html
> +    <link rel="stylesheet" href="style.css">
are you including your style sheet twice?

2018-08-14 22:19 UTC, richgurney commented on Game1/Game1.html
> +    <link rel="stylesheet" href="style.css">
Game 1 - Isn't working for me lets take a look in the morning

2018-08-15 09:55 UTC, VMistry commented
I have changed the CSS(style.css) and Javascript(script.js) files to CSS(game2Style.css) and Javascript(game2Script.js) in the Game2 folder.

2018-08-15 10:33 UTC, richgurney approved these changes

2018-08-15 10:33 UTC, richgurney commented on Game1/script.js
> +async function createLevel(){
What does this mean?

2018-08-15 10:33 UTC, richgurney commented on Game1/script.js
> +//compare the computer generated array with the array created by player.
Nice comments

2018-08-15 10:59 UTC, AEJackson approved these changes

2018-08-15 11:00 UTC, merged